package com.example.kotryn.states;

public enum State {
    /*0*/UNKNOWN,
    /*1*/CALCULATING_SAMPLE_COUNT_COMPLETED,
    /*2*/CALCULATING_SAMPLE_COUNT_FAILED,
    /*3*/CALCULATING_SAMPLE_COUNT_IN_PROGRESS,
    /*4*/ESTIMATING_WORST_CASE_DISTRIBUTIONS_COMPLETED,
    /*5*/ESTIMATING_WORST_CASE_DISTRIBUTIONS_FAILED,
    /*6*/ESTIMATING_WORST_CASE_DISTRIBUTIONS_IN_PROGRESS,
    /*7*/ESTIMATING_WORST_CASE_DISTRIBUTIONS_SETUP,
    /*8*/OBTAINING_PERIOD_OF_ANALYSIS,
    /*9*/OBTAINING_RETURN_PERIOD,
    /*10*/SEARCHING_FOR_STOCKS_COMPLETED,
    /*11*/SEARCHING_FOR_STOCKS_FAILED,
    /*12*/SEARCHING_FOR_STOCKS_IN_PROGRESS,
}
