package com.example.kotryn.processes;

public enum ProcessType {
    UNKNOWN,
    SEARCHING_FOR_STOCKS,
    CALCULATING_SAMPLE_COUNT,
    ESTIMATING_WORST_CASE_DISTRIBUTIONS,
    ESTIMATING_GROWTH_STOCKS,
    ESTIMATING_WORST_CASE_COPULA,
    BUILDING_ROBUST_PORTFOLIO,
    CALCULATING_STATISTIC,
}
