package com.kotryn.csv;

public enum File {
    FIRST_STOCK,
    CALCULATING_SAMPLE_COUNT,
    ESTIMATING_WORST_CASE_DISTRIBUTION,
    ESTIMATING_GROWTH_STOCKS,
    ESTIMATING_WORST_CASE_T_COPULA,
    ESTIMATING_WORST_CASE_CLAYTON_COPULA,
    BUILDING_ROBUST_PORTFOLIO,
    CALCULATING_STATISTIC
}
